# Use a lightweight Node.js image with ARM64 architecture
FROM node:14-bullseye-slim

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the application code
COPY . .

# Expose port 8000
EXPOSE 8000

# Start the server
CMD ["node", "app.js"]
