# Use the official MySQL image
FROM mysql:latest

# Set the root password and create a database
ENV MYSQL_ROOT_PASSWORD=mysecretpassword
ENV MYSQL_DATABASE=mydatabase

# Copy the SQL initialization script
COPY ./database.sql /docker-entrypoint-initdb.d/

# Expose port 3306
EXPOSE 3306
